### ISSUE TITLE
y axis rescale with time filtering

### ISSUE THREAD

**Issue by seabbs** [hamishgibbs/rt_vis#13]
At the moment the y axis is static as time is filtered. It would be great if this was dynamic.

**Comment by seabbs** [comment]
In a related note having some power to zoom the y axis (perhaps by tuning the truncation setting you have added) would be awesome.

**Comment by hamishgibbs** [comment]
It seems that the y axis is being redefined when time is filtered, but because the ymax value tends to be the final value in the timeseries for `casesInfection` and `casesReport` in particular, there is no change in the y axis when time is filtered. This could be improved by a more custom way to filter by time - a slider?

**Comment by seabbs** [comment]
yup makes sense and agree. Perhaps for the short term a more severe cut-off on the uncertainty (say 5* and not 10*). I think our forecasts are too uncertain anyway at the moment.

**Comment by hamishgibbs** [comment]
This has been changed to 5 * max observed cases in #37 and the y axis issue should also be addressed.
